services:
  yolo:
    build:
      args:
        CLIENT_SRC_FOLDER: $CLIENT_SRC_FOLDER
        CLIENT_WSP_FOLDER: $CLIENT_WSP_FOLDER
        HOST_WSP_FOLDER: $HOST_WSP_FOLDER
        HOST_SRC_FOLDER: $HOST_SRC_FOLDER
        REQUIREMENTS_FILE: $REQUIREMENTS_FILE
        ROS_MODULE_NAME: ros_yolov7
      context: $DOCKER_CONTEXT
      dockerfile: $DOCKERFILE
    command: bash -c 'source devel/setup.bash && roslaunch ros_yolov7 pose_estimate.launch'
    container_name: $DOCKER_COMPOSE_CONTAINER_NAME
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['${DEVICE}']
    env_file: $DOCKER_COMPOSE_ENV_FILE
    network_mode: host
    restart: unless-stopped
    volumes:
      - $DOCKER_CONTEXT/$MODULE_PATH/launch:$CLIENT_SRC_FOLDER/$ROS_MODULE_NAME/launch
      - $DOCKER_CONTEXT/$MODULE_PATH/msg:$CLIENT_SRC_FOLDER/$ROS_MODULE_NAME/msg
      - $DOCKER_CONTEXT/$MODULE_PATH/package.xml:$CLIENT_SRC_FOLDER/$ROS_MODULE_NAME/package.xml:rw
      - $DOCKER_CONTEXT/$MODULE_PATH/requirements.txt:$CLIENT_SRC_FOLDER/$ROS_MODULE_NAME/requirements.txt:rw
      - $DOCKER_CONTEXT/$MODULE_PATH/scripts:$CLIENT_SRC_FOLDER/$ROS_MODULE_NAME/scripts
      - $DOCKER_CONTEXT/$MODULE_PATH/src:$CLIENT_SRC_FOLDER/$ROS_MODULE_NAME/src
      - $HOST_CFG_FOLDER:$CLIENT_CFG_FOLDER
      - $HOST_DAT_FOLDER:$CLIENT_DAT_FOLDER
      - $X11_SOCKET:$X11_SOCKET
    working_dir: $CLIENT_WSP_FOLDER
