version: "3.9"
services:
  ros_yolo:
    working_dir: $WORKSPACE_NAME
    command: bash -c "source devel/setup.bash && roslaunch ros_yolov7 pose_estimate.launch"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: ros-yolo
    tty: true
    build:
      context: $DOCKER_CONTEXT
      dockerfile: $DOCKERFILE
      args:
        VIRTUAL_ENV: $VIRTUAL_ENV
        WORKSPACE_NAME: $WORKSPACE_NAME
        REQUIREMENTS_FILE: $REQUIREMENTS_FILE
        HOST_WORKSPACE_FOLDER: $HOST_WORKSPACE_FOLDER
        CLIENT_SRC_FOLDER: $CLIENT_SRC_FOLDER
        HOST_WORKSPACE_SRC_FOLDER: $HOST_WORKSPACE_SRC_FOLDER
    env_file: $DOCKER_COMPOSE_ENV_FILE
    volumes:
      - $HOST_CONFIG_FOLDER:$ROS_MUDIALBOT_CONFIG_PATH
      - $HOST_DATA_FOLDER:$DATA_FOLDER
      - $X11_SOCKET:$X11_SOCKET
    restart: always
    network_mode: host

