version: '3.9'
services:
  yolo:
    build:
      args:
        CLIENT_SRC_FOLDER: $CLIENT_SRC_FOLDER
        HOST_WORKSPACE_FOLDER: $HOST_WORKSPACE_FOLDER
        HOST_WORKSPACE_SRC_FOLDER: $HOST_WORKSPACE_SRC_FOLDER
        REQUIREMENTS_FILE: $REQUIREMENTS_FILE
        ROS_MODULE_NAME: ros_yolov7
        VIRTUAL_ENV: $VIRTUAL_ENV
        WORKSPACE_NAME: $WORKSPACE_NAME
      context: $DOCKER_CONTEXT
      dockerfile: $DOCKERFILE
    command: bash -c 'source devel/setup.bash && roslaunch ros_yolov7 pose_estimate.launch'
    container_name: yolo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    env_file: $DOCKER_COMPOSE_ENV_FILE
    network_mode: host
    restart: unless-stopped
    tty: true
    volumes:
      - $HOST_CONFIG_FOLDER:$ROS_MUDIALBOT_CONFIG_PATH
      - $HOST_DATA_FOLDER:$DATA_FOLDER
      - $X11_SOCKET:$X11_SOCKET
    working_dir: $WORKSPACE_NAME

